// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC81K3Ml169p_l9y4DojSwI5iGYvCMn-_s',
    appId: '1:723861394548:web:a01bd12388910b6a73ed21',
    messagingSenderId: '723861394548',
    projectId: 'new-project-1-fe243',
    authDomain: 'new-project-1-fe243.firebaseapp.com',
    storageBucket: 'new-project-1-fe243.appspot.com',
    measurementId: 'G-TDNZCP8C16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoOU-e2EDmn1TIwM9sFA64s6afNIOBpSg',
    appId: '1:723861394548:android:f10aaa019dc77c3f73ed21',
    messagingSenderId: '723861394548',
    projectId: 'new-project-1-fe243',
    storageBucket: 'new-project-1-fe243.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzYv6wTCezdcr-vhd6iEhuh9c0xeR1nI4',
    appId: '1:723861394548:ios:426d9c469518e16773ed21',
    messagingSenderId: '723861394548',
    projectId: 'new-project-1-fe243',
    storageBucket: 'new-project-1-fe243.appspot.com',
    iosBundleId: 'com.example.sk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzYv6wTCezdcr-vhd6iEhuh9c0xeR1nI4',
    appId: '1:723861394548:ios:59456c3adf8e19f773ed21',
    messagingSenderId: '723861394548',
    projectId: 'new-project-1-fe243',
    storageBucket: 'new-project-1-fe243.appspot.com',
    iosBundleId: 'com.example.sk.RunnerTests',
  );
}
